### ISSUE TITLE
Add music from other Ace Attorney games

### ISSUE THREAD

**Issue by jonatep** [LuisMayo/ace-attorney-twitter-bot#19]
I think it would be cool to add the trial and pursuit music from Justice for All and/or Trials and Tribulations, so it is selected randomly every time the bot is called, or it is specified as an argument in the mention. For example, if you want the music to be from Justice for All, you must mention the bot like this: "@aceCourtbot render, music=JFA"

**Comment by jonatep** [comment]
I just realized I should have opened this issue here https://github.com/LuisMayo/ace-attorney-bot/tree/b16d85b079dafe3d291a539a57a1763a749d5969, as that's the part involved with the video rendering. Sorry for the mistake

**Comment by LuisMayo** [comment]
Don't worry, both issues need to be created as both the rendering engine needs to support the option and the twitter bot needs to parse the command.

And thanks a lot for the suggestion, I find this one particularly interesting and shouldn't be hard to implement.
Thanks a lot!

**Comment by LuisMayo** [comment]
Depends on https://github.com/LuisMayo/ace-attorney-bot/issues/26
