### ISSUE TITLE
user abusing bot to harass others

### ISSUE THREAD

**Issue by girlmaya** [LuisMayo/ace-attorney-twitter-bot#41]
take a look at [@ShinyLegendary's use of the bot](https://twitter.com/search?q=%40aceCourtBot%20from%3A%40ShinyLegendary&src=typed_query&f=live). she is making perhaps 10 requests per hour today. i don't know if you blacklist users but it would be ideal in this situation

**Comment by LuisMayo** [comment]
Moving it to a discussion
