### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by reibitto** [LuisMayo/ace-attorney-twitter-bot#44]
I'm curious, is CJK supposed to be supported? It seems that the bot can output hiragana fine but it ignored kanji and left those parts blank.

I wonder how hard it would be to support multiple languages. Is it a matter of providing a font?

**Comment by reibitto** [comment]
I ran an additional test here. Confirmed that it can't handle kanji and hangul.
https://twitter.com/aceCourtBot/status/1441373453475479558

**Comment by exoego** [comment]
Maybe upstream issue?
https://github.com/LuisMayo/objection_engine/issues/37

**Comment by LuisMayo** [comment]
It's an upstream issue as @exoego pointed out. I have given more [there](https://github.com/LuisMayo/objection_engine/issues/37#issuecomment-926693357)

**Comment by reibitto** [comment]
Oops, sorry, I didn't notice that other project. Thanks. In that case I guess I should close this issue.
