### ISSUE TITLE
Issue rendering whitespace only names on Twitter

### ISSUE THREAD

**Issue by QuantumFractal** [LuisMayo/ace-attorney-twitter-bot#55]
Hey Luis, 

I noticed that when I use the bot with my twitter account [@tmoll](https://twitter.com/tmoll_) which uses a whitespace character name, it doesn't render in the bot.

Thread: https://twitter.com/tmoll_/status/1516931029633667072?s=20&t=msFYZQ2HP_chV_cB9c77kg
Render: https://cdn.moll.dev/content/media/random/1517247987419738113.mp4

**Comment by LuisMayo** [comment]
Closed by #56
