### ISSUE TITLE
Document about MongoDB / Consider migrating to Mongita

### ISSUE THREAD

**Issue by saschanaz** [LuisMayo/ace-attorney-twitter-bot#59]
39c569e7c89755e2c9058df618a8df325e5fc080 added pymongo dependency but readme does not say about that 👀

Edit: Please consider [Mongita](https://pypi.org/project/mongita/) btw. MongoDB installation is not very straightforward especially for database newcomers, and Mongita requires no installation. This way you don't have to document anything about MongoDB, and the migration is more than simple as it's (nearly) a drop-in replacement:

```diff
- from pymongo import MongoClient
- mongo_client = MongoClient('mongodb://localhost/')
+ from mongita import MongitaClientDisk
+ mongo_client = MongitaClientDisk()
```

**Comment by LuisMayo** [comment]
I've been taking a look to this. Removing MongoDB is not something I want happening. But Mongita has clear advantages in ease of installation

So this is what I'd like to do
1. Add an environmental variable pointing to the MongoDB URL
2. In runtime, if the env variable is set, use MongoDB pointing to that URL
3. If it doesn't exist, use Mongita

This way, administrators can operate without even knowing Mongita is working. But more advanced admins which may need full MongoDB can still use it if they choose to

Thanks for the issue
